---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nickjufg/lascoinstitute.org
    - /bin/cp -R /home/nickjufg/repositories/lascoinstitute/conference24 $DEPLOYPATH
    - /bin/cp -R /home/nickjufg/repositories/lascoinstitute   $DEPLOYPATH
    - /bin/cp /home/nickjufg/repositories/lascoinstitute/*.html     $DEPLOYPATH
    - /bin/cp /home/nickjufg/repositories/lascoinstitute/*.htm      $DEPLOYPATH
    - /bin/cp /home/nickjufg/repositories/lascoinstitute/*.*      $DEPLOYPATH